<?php
/**
 * PayoutApi
 * PHP version 7.4
 *
 * @category Class
 * @package  MassPayPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MassPay API
 *
 * MassPay API
 *
 * The version of the OpenAPI document: 0.1.4
 * Contact: info@masspay.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MassPayPhpSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use MassPayPhpSdk\ApiException;
use MassPayPhpSdk\Configuration;
use MassPayPhpSdk\HeaderSelector;
use MassPayPhpSdk\ObjectSerializer;

/**
 * PayoutApi Class Doc Comment
 *
 * @category Class
 * @package  MassPayPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PayoutApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'commitPayoutTxn' => [
            'application/json',
        ],
        'getPayoutStatus' => [
            'application/json',
        ],
        'getTransactionConfirmationDetails' => [
            'application/json',
        ],
        'getUserPayoutsByToken' => [
            'application/json',
        ],
        'initiatePayout' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation commitPayoutTxn
     *
     * Commit payout transaction
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['commitPayoutTxn'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MassPayPhpSdk\Model\PayoutTxnCommitResp|\MassPayPhpSdk\Model\Exception
     */
    public function commitPayoutTxn($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['commitPayoutTxn'][0])
    {
        list($response) = $this->commitPayoutTxnWithHttpInfo($user_token, $payout_token, $idempotency_key, $contentType);
        return $response;
    }

    /**
     * Operation commitPayoutTxnWithHttpInfo
     *
     * Commit payout transaction
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['commitPayoutTxn'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MassPayPhpSdk\Model\PayoutTxnCommitResp|\MassPayPhpSdk\Model\Exception, HTTP status code, HTTP response headers (array of strings)
     */
    public function commitPayoutTxnWithHttpInfo($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['commitPayoutTxn'][0])
    {
        $request = $this->commitPayoutTxnRequest($user_token, $payout_token, $idempotency_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MassPayPhpSdk\Model\PayoutTxnCommitResp' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MassPayPhpSdk\Model\PayoutTxnCommitResp' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MassPayPhpSdk\Model\PayoutTxnCommitResp', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 405:
                    if ('\MassPayPhpSdk\Model\Exception' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MassPayPhpSdk\Model\Exception' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MassPayPhpSdk\Model\Exception', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MassPayPhpSdk\Model\PayoutTxnCommitResp';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MassPayPhpSdk\Model\PayoutTxnCommitResp',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MassPayPhpSdk\Model\Exception',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation commitPayoutTxnAsync
     *
     * Commit payout transaction
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['commitPayoutTxn'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function commitPayoutTxnAsync($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['commitPayoutTxn'][0])
    {
        return $this->commitPayoutTxnAsyncWithHttpInfo($user_token, $payout_token, $idempotency_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation commitPayoutTxnAsyncWithHttpInfo
     *
     * Commit payout transaction
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['commitPayoutTxn'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function commitPayoutTxnAsyncWithHttpInfo($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['commitPayoutTxn'][0])
    {
        $returnType = '\MassPayPhpSdk\Model\PayoutTxnCommitResp';
        $request = $this->commitPayoutTxnRequest($user_token, $payout_token, $idempotency_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'commitPayoutTxn'
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['commitPayoutTxn'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function commitPayoutTxnRequest($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['commitPayoutTxn'][0])
    {

        // verify the required parameter 'user_token' is set
        if ($user_token === null || (is_array($user_token) && count($user_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_token when calling commitPayoutTxn'
            );
        }

        // verify the required parameter 'payout_token' is set
        if ($payout_token === null || (is_array($payout_token) && count($payout_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payout_token when calling commitPayoutTxn'
            );
        }



        $resourcePath = '/payout/{user_token}/{payout_token}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }

        // path params
        if ($user_token !== null) {
            $resourcePath = str_replace(
                '{' . 'user_token' . '}',
                ObjectSerializer::toPathValue($user_token),
                $resourcePath
            );
        }
        // path params
        if ($payout_token !== null) {
            $resourcePath = str_replace(
                '{' . 'payout_token' . '}',
                ObjectSerializer::toPathValue($payout_token),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPayoutStatus
     *
     * Get status of a payout by payout token
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $force_status_update Attempts to get an updated status update from the payout destination (optional, default to false)
     * @param  bool $include_payer_logo Whether to include the payer logo in base64 format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutStatus'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MassPayPhpSdk\Model\PayoutTxnResp|\MassPayPhpSdk\Model\Exception
     */
    public function getPayoutStatus($user_token, $payout_token, $idempotency_key = null, $force_status_update = false, $include_payer_logo = null, string $contentType = self::contentTypes['getPayoutStatus'][0])
    {
        list($response) = $this->getPayoutStatusWithHttpInfo($user_token, $payout_token, $idempotency_key, $force_status_update, $include_payer_logo, $contentType);
        return $response;
    }

    /**
     * Operation getPayoutStatusWithHttpInfo
     *
     * Get status of a payout by payout token
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $force_status_update Attempts to get an updated status update from the payout destination (optional, default to false)
     * @param  bool $include_payer_logo Whether to include the payer logo in base64 format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutStatus'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MassPayPhpSdk\Model\PayoutTxnResp|\MassPayPhpSdk\Model\Exception, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPayoutStatusWithHttpInfo($user_token, $payout_token, $idempotency_key = null, $force_status_update = false, $include_payer_logo = null, string $contentType = self::contentTypes['getPayoutStatus'][0])
    {
        $request = $this->getPayoutStatusRequest($user_token, $payout_token, $idempotency_key, $force_status_update, $include_payer_logo, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MassPayPhpSdk\Model\PayoutTxnResp' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MassPayPhpSdk\Model\PayoutTxnResp' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MassPayPhpSdk\Model\PayoutTxnResp', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 405:
                    if ('\MassPayPhpSdk\Model\Exception' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MassPayPhpSdk\Model\Exception' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MassPayPhpSdk\Model\Exception', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MassPayPhpSdk\Model\PayoutTxnResp';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MassPayPhpSdk\Model\PayoutTxnResp',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MassPayPhpSdk\Model\Exception',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPayoutStatusAsync
     *
     * Get status of a payout by payout token
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $force_status_update Attempts to get an updated status update from the payout destination (optional, default to false)
     * @param  bool $include_payer_logo Whether to include the payer logo in base64 format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPayoutStatusAsync($user_token, $payout_token, $idempotency_key = null, $force_status_update = false, $include_payer_logo = null, string $contentType = self::contentTypes['getPayoutStatus'][0])
    {
        return $this->getPayoutStatusAsyncWithHttpInfo($user_token, $payout_token, $idempotency_key, $force_status_update, $include_payer_logo, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPayoutStatusAsyncWithHttpInfo
     *
     * Get status of a payout by payout token
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $force_status_update Attempts to get an updated status update from the payout destination (optional, default to false)
     * @param  bool $include_payer_logo Whether to include the payer logo in base64 format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPayoutStatusAsyncWithHttpInfo($user_token, $payout_token, $idempotency_key = null, $force_status_update = false, $include_payer_logo = null, string $contentType = self::contentTypes['getPayoutStatus'][0])
    {
        $returnType = '\MassPayPhpSdk\Model\PayoutTxnResp';
        $request = $this->getPayoutStatusRequest($user_token, $payout_token, $idempotency_key, $force_status_update, $include_payer_logo, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPayoutStatus'
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $force_status_update Attempts to get an updated status update from the payout destination (optional, default to false)
     * @param  bool $include_payer_logo Whether to include the payer logo in base64 format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPayoutStatusRequest($user_token, $payout_token, $idempotency_key = null, $force_status_update = false, $include_payer_logo = null, string $contentType = self::contentTypes['getPayoutStatus'][0])
    {

        // verify the required parameter 'user_token' is set
        if ($user_token === null || (is_array($user_token) && count($user_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_token when calling getPayoutStatus'
            );
        }

        // verify the required parameter 'payout_token' is set
        if ($payout_token === null || (is_array($payout_token) && count($payout_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payout_token when calling getPayoutStatus'
            );
        }





        $resourcePath = '/payout/{user_token}/{payout_token}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $force_status_update,
            'force_status_update', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_payer_logo,
            'include_payer_logo', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }

        // path params
        if ($user_token !== null) {
            $resourcePath = str_replace(
                '{' . 'user_token' . '}',
                ObjectSerializer::toPathValue($user_token),
                $resourcePath
            );
        }
        // path params
        if ($payout_token !== null) {
            $resourcePath = str_replace(
                '{' . 'payout_token' . '}',
                ObjectSerializer::toPathValue($payout_token),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTransactionConfirmationDetails
     *
     * Get transaction confirmation details
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionConfirmationDetails'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MassPayPhpSdk\Model\GetTransactionConfirmationDetails200Response
     */
    public function getTransactionConfirmationDetails($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['getTransactionConfirmationDetails'][0])
    {
        list($response) = $this->getTransactionConfirmationDetailsWithHttpInfo($user_token, $payout_token, $idempotency_key, $contentType);
        return $response;
    }

    /**
     * Operation getTransactionConfirmationDetailsWithHttpInfo
     *
     * Get transaction confirmation details
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionConfirmationDetails'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MassPayPhpSdk\Model\GetTransactionConfirmationDetails200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTransactionConfirmationDetailsWithHttpInfo($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['getTransactionConfirmationDetails'][0])
    {
        $request = $this->getTransactionConfirmationDetailsRequest($user_token, $payout_token, $idempotency_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MassPayPhpSdk\Model\GetTransactionConfirmationDetails200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MassPayPhpSdk\Model\GetTransactionConfirmationDetails200Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MassPayPhpSdk\Model\GetTransactionConfirmationDetails200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MassPayPhpSdk\Model\GetTransactionConfirmationDetails200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MassPayPhpSdk\Model\GetTransactionConfirmationDetails200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTransactionConfirmationDetailsAsync
     *
     * Get transaction confirmation details
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionConfirmationDetails'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionConfirmationDetailsAsync($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['getTransactionConfirmationDetails'][0])
    {
        return $this->getTransactionConfirmationDetailsAsyncWithHttpInfo($user_token, $payout_token, $idempotency_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTransactionConfirmationDetailsAsyncWithHttpInfo
     *
     * Get transaction confirmation details
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionConfirmationDetails'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionConfirmationDetailsAsyncWithHttpInfo($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['getTransactionConfirmationDetails'][0])
    {
        $returnType = '\MassPayPhpSdk\Model\GetTransactionConfirmationDetails200Response';
        $request = $this->getTransactionConfirmationDetailsRequest($user_token, $payout_token, $idempotency_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTransactionConfirmationDetails'
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  string $payout_token Token representing the trsanaction. Retrieved from &#x60;/payout/{user_token}&#x60; (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionConfirmationDetails'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTransactionConfirmationDetailsRequest($user_token, $payout_token, $idempotency_key = null, string $contentType = self::contentTypes['getTransactionConfirmationDetails'][0])
    {

        // verify the required parameter 'user_token' is set
        if ($user_token === null || (is_array($user_token) && count($user_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_token when calling getTransactionConfirmationDetails'
            );
        }

        // verify the required parameter 'payout_token' is set
        if ($payout_token === null || (is_array($payout_token) && count($payout_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payout_token when calling getTransactionConfirmationDetails'
            );
        }



        $resourcePath = '/payout/{user_token}/{payout_token}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }

        // path params
        if ($user_token !== null) {
            $resourcePath = str_replace(
                '{' . 'user_token' . '}',
                ObjectSerializer::toPathValue($user_token),
                $resourcePath
            );
        }
        // path params
        if ($payout_token !== null) {
            $resourcePath = str_replace(
                '{' . 'payout_token' . '}',
                ObjectSerializer::toPathValue($payout_token),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUserPayoutsByToken
     *
     * Get history of payouts by user token
     *
     * @param  string $user_token The user token that needs to be fetched. (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $include_payer_logos Whether to include the payers logo in base64 format. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPayoutsByToken'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MassPayPhpSdk\Model\PayoutTxnResp[]
     */
    public function getUserPayoutsByToken($user_token, $idempotency_key = null, $include_payer_logos = false, string $contentType = self::contentTypes['getUserPayoutsByToken'][0])
    {
        list($response) = $this->getUserPayoutsByTokenWithHttpInfo($user_token, $idempotency_key, $include_payer_logos, $contentType);
        return $response;
    }

    /**
     * Operation getUserPayoutsByTokenWithHttpInfo
     *
     * Get history of payouts by user token
     *
     * @param  string $user_token The user token that needs to be fetched. (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $include_payer_logos Whether to include the payers logo in base64 format. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPayoutsByToken'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MassPayPhpSdk\Model\PayoutTxnResp[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getUserPayoutsByTokenWithHttpInfo($user_token, $idempotency_key = null, $include_payer_logos = false, string $contentType = self::contentTypes['getUserPayoutsByToken'][0])
    {
        $request = $this->getUserPayoutsByTokenRequest($user_token, $idempotency_key, $include_payer_logos, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MassPayPhpSdk\Model\PayoutTxnResp[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MassPayPhpSdk\Model\PayoutTxnResp[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MassPayPhpSdk\Model\PayoutTxnResp[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MassPayPhpSdk\Model\PayoutTxnResp[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MassPayPhpSdk\Model\PayoutTxnResp[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUserPayoutsByTokenAsync
     *
     * Get history of payouts by user token
     *
     * @param  string $user_token The user token that needs to be fetched. (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $include_payer_logos Whether to include the payers logo in base64 format. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPayoutsByToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserPayoutsByTokenAsync($user_token, $idempotency_key = null, $include_payer_logos = false, string $contentType = self::contentTypes['getUserPayoutsByToken'][0])
    {
        return $this->getUserPayoutsByTokenAsyncWithHttpInfo($user_token, $idempotency_key, $include_payer_logos, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUserPayoutsByTokenAsyncWithHttpInfo
     *
     * Get history of payouts by user token
     *
     * @param  string $user_token The user token that needs to be fetched. (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $include_payer_logos Whether to include the payers logo in base64 format. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPayoutsByToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserPayoutsByTokenAsyncWithHttpInfo($user_token, $idempotency_key = null, $include_payer_logos = false, string $contentType = self::contentTypes['getUserPayoutsByToken'][0])
    {
        $returnType = '\MassPayPhpSdk\Model\PayoutTxnResp[]';
        $request = $this->getUserPayoutsByTokenRequest($user_token, $idempotency_key, $include_payer_logos, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUserPayoutsByToken'
     *
     * @param  string $user_token The user token that needs to be fetched. (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  bool $include_payer_logos Whether to include the payers logo in base64 format. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPayoutsByToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUserPayoutsByTokenRequest($user_token, $idempotency_key = null, $include_payer_logos = false, string $contentType = self::contentTypes['getUserPayoutsByToken'][0])
    {

        // verify the required parameter 'user_token' is set
        if ($user_token === null || (is_array($user_token) && count($user_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_token when calling getUserPayoutsByToken'
            );
        }




        $resourcePath = '/payout/{user_token}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_payer_logos,
            'include_payer_logos', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }

        // path params
        if ($user_token !== null) {
            $resourcePath = str_replace(
                '{' . 'user_token' . '}',
                ObjectSerializer::toPathValue($user_token),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation initiatePayout
     *
     * Initiate a payout transaction
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  \MassPayPhpSdk\Model\PayoutTxn $payout_txn Payout parameters for a quote (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  float $limit Limit amount for transaction amount + fee. If fee + amount are higher than the limit, the output will automatically adjust to maximize the possible amount sent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initiatePayout'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MassPayPhpSdk\Model\PayoutTxnResp|\MassPayPhpSdk\Model\Exception
     */
    public function initiatePayout($user_token, $payout_txn, $idempotency_key = null, $limit = null, string $contentType = self::contentTypes['initiatePayout'][0])
    {
        list($response) = $this->initiatePayoutWithHttpInfo($user_token, $payout_txn, $idempotency_key, $limit, $contentType);
        return $response;
    }

    /**
     * Operation initiatePayoutWithHttpInfo
     *
     * Initiate a payout transaction
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  \MassPayPhpSdk\Model\PayoutTxn $payout_txn Payout parameters for a quote (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  float $limit Limit amount for transaction amount + fee. If fee + amount are higher than the limit, the output will automatically adjust to maximize the possible amount sent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initiatePayout'] to see the possible values for this operation
     *
     * @throws \MassPayPhpSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MassPayPhpSdk\Model\PayoutTxnResp|\MassPayPhpSdk\Model\Exception, HTTP status code, HTTP response headers (array of strings)
     */
    public function initiatePayoutWithHttpInfo($user_token, $payout_txn, $idempotency_key = null, $limit = null, string $contentType = self::contentTypes['initiatePayout'][0])
    {
        $request = $this->initiatePayoutRequest($user_token, $payout_txn, $idempotency_key, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MassPayPhpSdk\Model\PayoutTxnResp' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MassPayPhpSdk\Model\PayoutTxnResp' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MassPayPhpSdk\Model\PayoutTxnResp', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 405:
                    if ('\MassPayPhpSdk\Model\Exception' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MassPayPhpSdk\Model\Exception' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MassPayPhpSdk\Model\Exception', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MassPayPhpSdk\Model\PayoutTxnResp';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MassPayPhpSdk\Model\PayoutTxnResp',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MassPayPhpSdk\Model\Exception',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation initiatePayoutAsync
     *
     * Initiate a payout transaction
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  \MassPayPhpSdk\Model\PayoutTxn $payout_txn Payout parameters for a quote (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  float $limit Limit amount for transaction amount + fee. If fee + amount are higher than the limit, the output will automatically adjust to maximize the possible amount sent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initiatePayout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function initiatePayoutAsync($user_token, $payout_txn, $idempotency_key = null, $limit = null, string $contentType = self::contentTypes['initiatePayout'][0])
    {
        return $this->initiatePayoutAsyncWithHttpInfo($user_token, $payout_txn, $idempotency_key, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation initiatePayoutAsyncWithHttpInfo
     *
     * Initiate a payout transaction
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  \MassPayPhpSdk\Model\PayoutTxn $payout_txn Payout parameters for a quote (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  float $limit Limit amount for transaction amount + fee. If fee + amount are higher than the limit, the output will automatically adjust to maximize the possible amount sent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initiatePayout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function initiatePayoutAsyncWithHttpInfo($user_token, $payout_txn, $idempotency_key = null, $limit = null, string $contentType = self::contentTypes['initiatePayout'][0])
    {
        $returnType = '\MassPayPhpSdk\Model\PayoutTxnResp';
        $request = $this->initiatePayoutRequest($user_token, $payout_txn, $idempotency_key, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'initiatePayout'
     *
     * @param  string $user_token Token representing the user to pay out (required)
     * @param  \MassPayPhpSdk\Model\PayoutTxn $payout_txn Payout parameters for a quote (required)
     * @param  string $idempotency_key Unique key to prevent duplicate processing (optional)
     * @param  float $limit Limit amount for transaction amount + fee. If fee + amount are higher than the limit, the output will automatically adjust to maximize the possible amount sent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initiatePayout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function initiatePayoutRequest($user_token, $payout_txn, $idempotency_key = null, $limit = null, string $contentType = self::contentTypes['initiatePayout'][0])
    {

        // verify the required parameter 'user_token' is set
        if ($user_token === null || (is_array($user_token) && count($user_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_token when calling initiatePayout'
            );
        }

        // verify the required parameter 'payout_txn' is set
        if ($payout_txn === null || (is_array($payout_txn) && count($payout_txn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payout_txn when calling initiatePayout'
            );
        }


        if ($limit !== null && !preg_match("/^[\\d.]+$/", $limit)) {
            throw new \InvalidArgumentException("invalid value for \"limit\" when calling PayoutApi.initiatePayout, must conform to the pattern /^[\\d.]+$/.");
        }
        

        $resourcePath = '/payout/{user_token}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }

        // path params
        if ($user_token !== null) {
            $resourcePath = str_replace(
                '{' . 'user_token' . '}',
                ObjectSerializer::toPathValue($user_token),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payout_txn)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payout_txn));
            } else {
                $httpBody = $payout_txn;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
